server:
  port: 8080
#权限认证框架配置
sa-token:

  token-name: satoken

  timeout: 2592000

  activity-timeout: -1

  is-concurrent: true

  is-share: true

  token-style: uuid

  jwt-secret-key: e10adc3949ba59abbe56e057f20f883e

  is-read-cookie: true
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/beautifulAPP?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 81192
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  #Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

